version: '3.8'

services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:10
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/${DB_NAME}
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - database
    entrypoint: [ "flyway", "migrate" ]

volumes:
  postgres_data: